[package]
name = "silkenweb-example-tauri-frontend"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
futures-signals = "0.3.24"
silkenweb = { git = "https://github.com/silkenweb/silkenweb" }
silkenweb-tauri = { git = "https://github.com/silkenweb/silkenweb" }
